# Generated by Django 5.2.17 on 2026-08-11 14:03

import content.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True)),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for cards and listings')),
                ('body', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Body')),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword the SEO writer is targeting', max_length=80)),
                ('seo_title', models.CharField(blank=True, max_length=70, validators=[content.validators.validate_seo_title])),
                ('seo_description', models.CharField(blank=True, max_length=160, validators=[content.validators.validate_seo_description])),
                ('canonical_url', models.URLField(blank=True)),
                ('robots_index', models.BooleanField(default=True)),
                ('robots_follow', models.BooleanField(default=True)),
                ('geo_summary', models.TextField(blank=True, help_text='Clear factual summary optimized for AI answer engines', validators=[content.validators.validate_geo_summary_quality])),
                ('geo_key_facts', models.JSONField(blank=True, default=list, help_text='["Fact 1", "Fact 2"]')),
                ('geo_entities', models.JSONField(blank=True, default=list, help_text='["مرد کوهستان", "راه سبز"]')),
                ('geo_faq', models.JSONField(blank=True, default=list, help_text='[{"question": "...", "answer": "..."}]', validators=[content.validators.validate_geo_faq])),
                ('schema_json', models.JSONField(blank=True, default=dict, help_text='Auto-generated JSON-LD for SEO/GEO (can be overridden)')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='articles/covers/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-published_at', '-created_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='content_art_status_4645e7_idx'), models.Index(fields=['slug'], name='content_art_slug_d82f31_idx')],
            },
        ),
    ]
