# Generated by Django 5.2.17 on 2026-08-11 14:23

import content.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentPillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('primary_keyword', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Content pillar',
                'verbose_name_plural': 'Content pillars',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='RedirectRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_path', models.CharField(help_text='e.g. /old-article/', max_length=255, unique=True)),
                ('to_path', models.CharField(help_text='e.g. /articles/new-slug/', max_length=255)),
                ('status_code', models.PositiveSmallIntegerField(choices=[(301, '301 Permanent'), (302, '302 Temporary')], default=301)),
                ('is_active', models.BooleanField(default=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Redirect rule',
                'verbose_name_plural': 'Redirect rules',
                'ordering': ['from_path'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='breadcrumb_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='article',
            name='content_role',
            field=models.CharField(choices=[('pillar', 'Pillar page'), ('cluster', 'Cluster article'), ('supporting', 'Supporting content'), ('standalone', 'Standalone')], db_index=True, default='standalone', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='editor_notes',
            field=models.TextField(blank=True, help_text='Private notes for SEO/editorial team (not public)'),
        ),
        migrations.AddField(
            model_name='article',
            name='internal_links',
            field=models.JSONField(blank=True, default=list, help_text='Suggested/used internal links: [{"title":"...","url":"..."}]'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_description',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/og/'),
        ),
        migrations.AddField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='article',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='article',
            name='search_intent',
            field=models.CharField(choices=[('informational', 'Informational'), ('navigational', 'Navigational'), ('commercial', 'Commercial'), ('transactional', 'Transactional')], db_index=True, default='informational', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='secondary_keywords',
            field=models.JSONField(blank=True, default=list, help_text='["keyword 2", "keyword 3"]'),
        ),
        migrations.AddField(
            model_name='article',
            name='word_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_entities',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_faq',
            field=models.JSONField(blank=True, default=list, validators=[content.validators.validate_geo_faq]),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_key_facts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='article',
            name='schema_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.category')),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.category'),
        ),
        migrations.AddField(
            model_name='article',
            name='pillar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.contentpillar'),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.tag'),
        ),
        migrations.CreateModel(
            name='TopicCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('target_keyword', models.CharField(blank=True, max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pillar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='content.contentpillar')),
            ],
            options={
                'verbose_name': 'Topic cluster',
                'verbose_name_plural': 'Topic clusters',
                'ordering': ['pillar__title', 'title'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.topiccluster'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['content_role', 'search_intent'], name='content_art_content_ffbcd7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='topiccluster',
            unique_together={('pillar', 'slug')},
        ),
    ]
