# Generated by Django 5.2.17 on 2026-08-11 14:34

import content.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_contentpillar_redirectrule_tag_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقالات'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='contentpillar',
            options={'ordering': ['title'], 'verbose_name': 'ستون محتوا (Pillar)', 'verbose_name_plural': 'ستون\u200cهای محتوا (Pillars)'},
        ),
        migrations.AlterModelOptions(
            name='redirectrule',
            options={'ordering': ['from_path'], 'verbose_name': 'ریدایرکت', 'verbose_name_plural': 'ریدایرکت\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['name'], 'verbose_name': 'برچسب', 'verbose_name_plural': 'برچسب\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='topiccluster',
            options={'ordering': ['pillar__title', 'title'], 'verbose_name': 'خوشه موضوعی (Cluster)', 'verbose_name_plural': 'خوشه\u200cهای موضوعی (Clusters)'},
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده'),
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن اصلی مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='breadcrumb_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='عنوان مسیر راهنما'),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='آدرس کنونیکال'),
        ),
        migrations.AlterField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.category', verbose_name='دسته\u200cبندی\u200cها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.topiccluster', verbose_name='خوشه موضوعی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_role',
            field=models.CharField(choices=[('pillar', 'صفحه ستون (Pillar)'), ('cluster', 'مقاله خوشه\u200cای (Cluster)'), ('supporting', 'محتوای پشتیبان'), ('standalone', 'مستقل')], db_index=True, default='standalone', max_length=20, verbose_name='نقش محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='تصویر شاخص'),
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='article',
            name='editor_notes',
            field=models.TextField(blank=True, help_text='فقط برای تیم محتوا/سئو؛ در سایت نمایش داده نمی\u200cشود', verbose_name='یادداشت داخلی تیم'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='برای کارت\u200cها و لیست مقالات', verbose_name='خلاصه کوتاه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='کلمه کلیدی اصلی که سئوکار روی آن کار می\u200cکند', max_length=80, verbose_name='کلمه کلیدی اصلی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_entities',
            field=models.JSONField(blank=True, default=list, help_text='["مرد کوهستان", "راه سبز"]', verbose_name='موجودیت\u200cهای برند/محصول'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_faq',
            field=models.JSONField(blank=True, default=list, help_text='[{"question":"سوال؟","answer":"پاسخ"}]', validators=[content.validators.validate_geo_faq], verbose_name='سوالات متداول GEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_key_facts',
            field=models.JSONField(blank=True, default=list, help_text='["حقیقت ۱", "حقیقت ۲"]', verbose_name='حقایق کلیدی GEO'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_summary',
            field=models.TextField(blank=True, help_text='یک خلاصه شفاف و قابل استناد برای ChatGPT، Perplexity و مشابه', validators=[content.validators.validate_geo_summary_quality], verbose_name='خلاصه GEO برای موتورهای هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='internal_links',
            field=models.JSONField(blank=True, default=list, help_text='[{"title":"عنوان","url":"/articles/.../"}]', verbose_name='لینک\u200cهای داخلی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_description',
            field=models.CharField(blank=True, max_length=160, verbose_name='توضیح شبکه\u200cهای اجتماعی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/og/', verbose_name='تصویر شبکه\u200cهای اجتماعی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='og_title',
            field=models.CharField(blank=True, max_length=70, verbose_name='عنوان شبکه\u200cهای اجتماعی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pillar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.contentpillar', verbose_name='ستون محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='زمان انتشار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='reading_time_minutes',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='زمان مطالعه (دقیقه)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='robots_follow',
            field=models.BooleanField(default=True, verbose_name='اجازه دنبال کردن لینک\u200cها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='robots_index',
            field=models.BooleanField(default=True, verbose_name='اجازه ایندکس'),
        ),
        migrations.AlterField(
            model_name='article',
            name='schema_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='داده ساخت\u200cیافته JSON-LD'),
        ),
        migrations.AlterField(
            model_name='article',
            name='search_intent',
            field=models.CharField(choices=[('informational', 'آگاهی\u200cبخش (Informational)'), ('navigational', 'هدایتی (Navigational)'), ('commercial', 'تجاری (Commercial)'), ('transactional', 'تراکنشی (Transactional)')], db_index=True, default='informational', max_length=20, verbose_name='نیت جستجو'),
        ),
        migrations.AlterField(
            model_name='article',
            name='secondary_keywords',
            field=models.JSONField(blank=True, default=list, help_text='مثال: ["عسل کوهستان", "راه سبز"]', verbose_name='کلمات کلیدی فرعی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, help_text='حداکثر حدود ۱۶۰ کاراکتر', max_length=160, validators=[content.validators.validate_seo_description], verbose_name='توضیحات سئو'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, help_text='حداکثر حدود ۷۰ کاراکتر', max_length=70, validators=[content.validators.validate_seo_title], verbose_name='عنوان سئو'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='نامک URL'),
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('in_review', 'در حال بررسی'), ('published', 'منتشر شده'), ('archived', 'بایگانی')], db_index=True, default='draft', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='content.tag', verbose_name='برچسب\u200cها'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='word_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='تعداد کلمات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='نام دسته'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='content.category', verbose_name='دسته والد'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=140, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='contentpillar',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='contentpillar',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات استراتژی'),
        ),
        migrations.AlterField(
            model_name='contentpillar',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='contentpillar',
            name='primary_keyword',
            field=models.CharField(blank=True, max_length=80, verbose_name='کلمه کلیدی اصلی'),
        ),
        migrations.AlterField(
            model_name='contentpillar',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='contentpillar',
            name='title',
            field=models.CharField(max_length=180, verbose_name='عنوان ستون محتوا'),
        ),
        migrations.AlterField(
            model_name='contentpillar',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی'),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='from_path',
            field=models.CharField(help_text='مثال: /old-article/', max_length=255, unique=True, verbose_name='مسیر مبدأ'),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='note',
            field=models.CharField(blank=True, max_length=255, verbose_name='یادداشت'),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='status_code',
            field=models.PositiveSmallIntegerField(choices=[(301, '۳۰۱ دائمی'), (302, '۳۰۲ موقت')], default=301, verbose_name='کد وضعیت'),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='to_path',
            field=models.CharField(help_text='مثال: /articles/new-slug/', max_length=255, verbose_name='مسیر مقصد'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=80, unique=True, verbose_name='نام برچسب'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='content.contentpillar', verbose_name='ستون محتوا'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, verbose_name='نامک'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='target_keyword',
            field=models.CharField(blank=True, max_length=80, verbose_name='کلمه کلیدی هدف'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='title',
            field=models.CharField(max_length=180, verbose_name='عنوان خوشه'),
        ),
    ]
