# Generated by Django 5.2.17 on 2026-08-11 14:39

import content.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_persian_labels'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentpillar',
            options={'ordering': ['title'], 'verbose_name': 'ستون محتوا', 'verbose_name_plural': 'ستون\u200cهای محتوا'},
        ),
        migrations.AlterModelOptions(
            name='topiccluster',
            options={'ordering': ['pillar__title', 'title'], 'verbose_name': 'خوشه موضوعی', 'verbose_name_plural': 'خوشه\u200cهای موضوعی'},
        ),
        migrations.AlterField(
            model_name='article',
            name='content_role',
            field=models.CharField(choices=[('pillar', 'صفحه ستون محتوا'), ('cluster', 'مقاله خوشه\u200cای'), ('supporting', 'محتوای پشتیبان'), ('standalone', 'مستقل')], db_index=True, default='standalone', max_length=20, verbose_name='نقش محتوا'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_entities',
            field=models.JSONField(blank=True, default=list, help_text='مثال: ["مرد کوهستان", "راه سبز", "عسل کوهستان"]', verbose_name='موجودیت\u200cهای برند و محصول'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_faq',
            field=models.JSONField(blank=True, default=list, help_text='هر تعداد سوال؛ مثال: [{"سوال":"مرد کوهستان چیست؟","پاسخ":"..."}]', validators=[content.validators.validate_geo_faq], verbose_name='سوالات متداول برای هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_key_facts',
            field=models.JSONField(blank=True, default=list, help_text='هر تعداد حقیقت؛ مثال: ["مرد کوهستان برند صنایع غذایی است", "راه سبز زنجیره ارزش یکپارچه است"]', verbose_name='حقایق کلیدی برای هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_summary',
            field=models.TextField(blank=True, help_text='خلاصه شفاف و قابل استناد برای پاسخ\u200cدهی هوش مصنوعی (چت\u200cجی\u200cپی\u200cتی، پرپلکسیتی و مشابه)', validators=[content.validators.validate_geo_summary_quality], verbose_name='خلاصه برای موتورهای هوش مصنوعی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='internal_links',
            field=models.JSONField(blank=True, default=list, help_text='هر تعداد لینک؛ مثال: [{"عنوان":"راه سبز","آدرس":"/articles/rah-sabz/"}]', verbose_name='لینک\u200cهای داخلی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='schema_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='داده ساخت\u200cیافته برای موتورهای جستجو'),
        ),
        migrations.AlterField(
            model_name='article',
            name='search_intent',
            field=models.CharField(choices=[('informational', 'آگاهی\u200cبخش'), ('navigational', 'هدایتی'), ('commercial', 'تجاری'), ('transactional', 'تراکنشی')], db_index=True, default='informational', max_length=20, verbose_name='نیت جستجو'),
        ),
        migrations.AlterField(
            model_name='article',
            name='secondary_keywords',
            field=models.JSONField(blank=True, default=list, help_text='هر تعداد کلمه که لازم دارید؛ مثال: ["عسل کوهستان", "راه سبز", "محصولات لبنی"]', verbose_name='کلمات کلیدی فرعی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='نامک آدرس'),
        ),
    ]
