# Generated by Django 5.2.17 on 2026-09-04 14:24

import content.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_persian_ui_polish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at', '-created_at'], 'verbose_name': 'مقاله', 'verbose_name_plural': 'مقاله\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='contentpillar',
            options={'ordering': ['title'], 'verbose_name': 'موضوع اصلی', 'verbose_name_plural': 'موضوع\u200cهای اصلی'},
        ),
        migrations.AlterModelOptions(
            name='redirectrule',
            options={'ordering': ['from_path'], 'verbose_name': 'آدرس قدیمی', 'verbose_name_plural': 'آدرس\u200cهای قدیمی'},
        ),
        migrations.AlterModelOptions(
            name='topiccluster',
            options={'ordering': ['pillar__title', 'title'], 'verbose_name': 'زیرموضوع', 'verbose_name_plural': 'زیرموضوع\u200cها'},
        ),
        migrations.AlterField(
            model_name='article',
            name='body',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='متن مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='breadcrumb_title',
            field=models.CharField(blank=True, max_length=120, verbose_name='نام کوتاه در مسیر صفحه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='canonical_url',
            field=models.URLField(blank=True, verbose_name='آدرس اصلی صفحه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.topiccluster', verbose_name='زیرموضوع'),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_role',
            field=models.CharField(choices=[('pillar', 'موضوع اصلی'), ('cluster', 'زیرموضوع'), ('supporting', 'نوشته کمکی'), ('standalone', 'نوشته جدا')], db_index=True, default='standalone', max_length=20, verbose_name='نوع نوشته'),
        ),
        migrations.AlterField(
            model_name='article',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/covers/', verbose_name='عکس بالای مقاله'),
        ),
        migrations.AlterField(
            model_name='article',
            name='editor_notes',
            field=models.TextField(blank=True, help_text='فقط تیم می\u200cبیند؛ روی سایت نمی\u200cآید', verbose_name='یادداشت برای همکار'),
        ),
        migrations.AlterField(
            model_name='article',
            name='excerpt',
            field=models.TextField(blank=True, help_text='روی کارت مقاله در سایت دیده می\u200cشود', verbose_name='خلاصه کوتاه'),
        ),
        migrations.AlterField(
            model_name='article',
            name='focus_keyword',
            field=models.CharField(blank=True, help_text='همان کلمه\u200cای که مردم در گوگل می\u200cنویسند', max_length=80, verbose_name='کلمهٔ اصلی جستجو'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_entities',
            field=models.JSONField(blank=True, default=list, help_text='مثال: ["مرد کوهستان", "راه سبز", "عسل کوهستان"]', verbose_name='نام\u200cهای برند و محصول در متن'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_faq',
            field=models.JSONField(blank=True, default=list, help_text='هر تعداد سوال؛ مثال: [{"سوال":"مرد کوهستان چیست؟","پاسخ":"..."}]', validators=[content.validators.validate_geo_faq], verbose_name='سوال و جواب'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_key_facts',
            field=models.JSONField(blank=True, default=list, help_text='هر تعداد حقیقت؛ مثال: ["مرد کوهستان برند صنایع غذایی است", "راه سبز زنجیره ارزش یکپارچه است"]', verbose_name='نکته\u200cهای مهم'),
        ),
        migrations.AlterField(
            model_name='article',
            name='geo_summary',
            field=models.TextField(blank=True, help_text='چند خط ساده که اگر کسی از چت\u200cبات\u200cها پرسید، جواب درست بدهند', validators=[content.validators.validate_geo_summary_quality], verbose_name='خلاصه برای پاسخ\u200cهای اینترنتی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='internal_links',
            field=models.JSONField(blank=True, default=list, help_text='هر تعداد لینک؛ مثال: [{"عنوان":"راه سبز","آدرس":"/articles/rah-sabz/"}]', verbose_name='لینک به صفحه\u200cهای دیگر سایت'),
        ),
        migrations.AlterField(
            model_name='article',
            name='pillar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='content.contentpillar', verbose_name='موضوع اصلی'),
        ),
        migrations.AlterField(
            model_name='article',
            name='robots_follow',
            field=models.BooleanField(default=True, verbose_name='لینک\u200cهای داخل متن دنبال شود'),
        ),
        migrations.AlterField(
            model_name='article',
            name='robots_index',
            field=models.BooleanField(default=True, verbose_name='در گوگل نشان داده شود'),
        ),
        migrations.AlterField(
            model_name='article',
            name='schema_json',
            field=models.JSONField(blank=True, default=dict, verbose_name='اطلاعات فنی برای گوگل'),
        ),
        migrations.AlterField(
            model_name='article',
            name='search_intent',
            field=models.CharField(choices=[('informational', 'می\u200cخواهد بداند'), ('navigational', 'دنبال یک صفحه مشخص است'), ('commercial', 'می\u200cخواهد مقایسه کند'), ('transactional', 'می\u200cخواهد بخرد')], db_index=True, default='informational', max_length=20, verbose_name='مخاطب دنبال چیست'),
        ),
        migrations.AlterField(
            model_name='article',
            name='secondary_keywords',
            field=models.JSONField(blank=True, default=list, help_text='هر تعداد که لازم دارید؛ مثال: ["عسل کوهستان", "راه سبز"]', verbose_name='کلمه\u200cهای نزدیک'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_description',
            field=models.CharField(blank=True, help_text='حدود ۱۶۰ حرف؛ همان دو خط خاکستری زیر عنوان', max_length=160, validators=[content.validators.validate_seo_description], verbose_name='توضیح در گوگل'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seo_title',
            field=models.CharField(blank=True, help_text='حدود ۷۰ حرف؛ همان عنوان آبی در نتایج گوگل', max_length=70, validators=[content.validators.validate_seo_title], verbose_name='عنوان در گوگل'),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=220, unique=True, verbose_name='آدرس صفحه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=140, unique=True, verbose_name='آدرس صفحه'),
        ),
        migrations.AlterField(
            model_name='contentpillar',
            name='description',
            field=models.TextField(blank=True, verbose_name='توضیح این موضوع'),
        ),
        migrations.AlterField(
            model_name='contentpillar',
            name='primary_keyword',
            field=models.CharField(blank=True, max_length=80, verbose_name='کلمهٔ اصلی که مردم جستجو می\u200cکنند'),
        ),
        migrations.AlterField(
            model_name='contentpillar',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, unique=True, verbose_name='آدرس صفحه'),
        ),
        migrations.AlterField(
            model_name='contentpillar',
            name='title',
            field=models.CharField(max_length=180, verbose_name='نام موضوع اصلی'),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='from_path',
            field=models.CharField(help_text='مثال: /old-article/', max_length=255, unique=True, verbose_name='آدرس قدیمی'),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='status_code',
            field=models.PositiveSmallIntegerField(choices=[(301, 'برای همیشه'), (302, 'موقت')], default=301, verbose_name='نوع هدایت'),
        ),
        migrations.AlterField(
            model_name='redirectrule',
            name='to_path',
            field=models.CharField(help_text='مثال: /articles/new-slug/', max_length=255, verbose_name='آدرس جدید'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=100, unique=True, verbose_name='آدرس صفحه'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='pillar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to='content.contentpillar', verbose_name='موضوع اصلی'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='slug',
            field=models.SlugField(allow_unicode=True, blank=True, max_length=200, verbose_name='آدرس صفحه'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='target_keyword',
            field=models.CharField(blank=True, max_length=80, verbose_name='کلمهٔ جستجو برای این زیرموضوع'),
        ),
        migrations.AlterField(
            model_name='topiccluster',
            name='title',
            field=models.CharField(max_length=180, verbose_name='نام زیرموضوع'),
        ),
    ]
