# Generated by Django 5.2.17 on 2026-09-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_article_options_alter_contentpillar_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MagazinePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(default='مجله مرد کوهستان', max_length=120, verbose_name='خط بالای عنوان')),
                ('hero_title', models.CharField(default='این راه سبز است', max_length=180, verbose_name='عنوان اصلی مجله')),
                ('search_placeholder', models.CharField(default='در مجله بگردید یک مسیر و یک طعم و یک نوشته', max_length=200, verbose_name='متن داخل جستجو')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
            ],
            options={
                'verbose_name': 'صفحه مجله',
                'verbose_name_plural': 'صفحه مجله',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['sort_order', 'name'], 'verbose_name': 'دسته\u200cبندی', 'verbose_name_plural': 'دسته\u200cبندی\u200cها'},
        ),
        migrations.AddField(
            model_name='category',
            name='magazine_image',
            field=models.ImageField(blank=True, help_text='اگر خالی باشد از مسیر ثابت زیر استفاده می\u200cشود', null=True, upload_to='magazine/categories/', verbose_name='عکس حلقه مجله'),
        ),
        migrations.AddField(
            model_name='category',
            name='magazine_image_path',
            field=models.CharField(blank=True, help_text='مثال: /magazine/png/png-sheep.png', max_length=255, verbose_name='مسیر عکس ثابت'),
        ),
        migrations.AddField(
            model_name='category',
            name='seo_title',
            field=models.CharField(blank=True, help_text='اگر خالی باشد همان نام دسته برای گوگل استفاده می\u200cشود', max_length=70, verbose_name='عنوان SEO دسته'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_on_magazine',
            field=models.BooleanField(default=True, help_text='اگر خاموش باشد فقط برای فیلتر مقاله می\u200cماند و در صفحه مجله دیده نمی\u200cشود', verbose_name='نمایش در حلقه\u200cهای مجله'),
        ),
        migrations.AddField(
            model_name='category',
            name='sort_order',
            field=models.PositiveIntegerField(db_index=True, default=100, help_text='عدد کوچکتر زودتر در حلقه\u200cهای مجله دیده می\u200cشود', verbose_name='ترتیب نمایش در مجله'),
        ),
    ]
