# Generated by Django 5.2.17 on 2026-08-31 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='نام دسته')),
                ('slug', models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='نامک')),
                ('description', models.TextField(blank=True, max_length=500, verbose_name='توضیحات')),
                ('domain', models.CharField(blank=True, choices=[('fresh_meat', 'گوشت تازه'), ('seafood', 'محصولات دریایی'), ('sausage_cold_cuts', 'سوسیس و کالباس'), ('ready_to_cook', 'آماده پخت'), ('ready_meals', 'غذای آماده'), ('dairy', 'لبنیات'), ('agriculture', 'کشاورزی و مزرعه'), ('bakery_culinary', 'نان و آشپزی')], max_length=32, verbose_name='دامنه')),
                ('kind', models.CharField(choices=[('navigation', 'ناوبری فروشگاه'), ('collection', 'مجموعه'), ('seasonal', 'فصلی'), ('promotion', 'پروموشن')], default='navigation', max_length=20, verbose_name='نوع')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='product.category', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته محصول',
                'verbose_name_plural': 'دسته\u200cهای محصول',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='نام')),
                ('slug', models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='نامک')),
                ('subtitle', models.CharField(blank=True, max_length=240, verbose_name='زیرعنوان')),
                ('short_description', models.CharField(blank=True, max_length=320, verbose_name='توضیح کوتاه')),
                ('domain', models.CharField(choices=[('fresh_meat', 'گوشت تازه'), ('seafood', 'محصولات دریایی'), ('sausage_cold_cuts', 'سوسیس و کالباس'), ('ready_to_cook', 'آماده پخت'), ('ready_meals', 'غذای آماده'), ('dairy', 'لبنیات'), ('agriculture', 'کشاورزی و مزرعه'), ('bakery_culinary', 'نان و آشپزی')], max_length=32, verbose_name='دامنه')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار تأیید'), ('active', 'فعال'), ('out_of_stock', 'ناموجود'), ('discontinued', 'توقف تولید'), ('archived', 'بایگانی')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('visibility', models.CharField(choices=[('public', 'عمومی'), ('hidden', 'مخفی'), ('b2c_only', 'فقط خرده\u200cفروشی'), ('b2b_only', 'فقط عمده\u200cفروشی')], default='public', max_length=16, verbose_name='نمایش')),
                ('sales_channel', models.CharField(choices=[('b2c', 'خرده\u200cفروشی'), ('b2b', 'عمده\u200cفروشی'), ('b2g', 'فروش سازمانی و بین\u200cالمللی'), ('all_three', 'هر سه')], default='b2c', max_length=16, verbose_name='کانال فروش')),
                ('unit_price_rial', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت (ریال)')),
                ('pricing_strategy', models.CharField(choices=[('fixed', 'قیمت ثابت'), ('per_kg', 'قیمت هر کیلوگرم'), ('per_100g', 'قیمت هر ۱۰۰ گرم')], default='fixed', max_length=12, verbose_name='قیمت\u200cگذاری')),
                ('unit_of_measure', models.CharField(choices=[('piece', 'عدد'), ('pack', 'بسته'), ('tray', 'سینی'), ('dozen', 'شل'), ('gram', 'گرم'), ('kilogram', 'کیلوگرم'), ('milliliter', 'میلی\u200cلیتر'), ('liter', 'لیتر')], default='piece', max_length=12, verbose_name='واحد')),
                ('net_weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن خالص (گرم)')),
                ('storage_class', models.CharField(choices=[('ambient', 'دمای محیط'), ('chilled', 'سرد (۲ تا ۸ درجه)'), ('frozen', 'منجمد (زیر ۱۸- درجه)')], default='chilled', max_length=10, verbose_name='نگهداری')),
                ('packaging_type', models.CharField(blank=True, choices=[('vacuum', 'وکیوم'), ('tray_film', 'سینی و نایلون'), ('bottle', 'بطری'), ('jar', 'شیشه'), ('carton', 'کارتن'), ('bulk', 'فله'), ('other', 'سایر')], default='other', max_length=12, verbose_name='بسته\u200cبندی')),
                ('halal_status', models.CharField(choices=[('certified', 'دارای گواهی حلال'), ('not_applicable', 'غیرمرتبط'), ('pending', 'در انتظار تأیید')], default='not_applicable', max_length=16, verbose_name='حلال')),
                ('allergens', models.JSONField(blank=True, default=list, verbose_name='آلرژن\u200cها')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('categories', models.ManyToManyField(blank=True, related_name='products', to='product.category', verbose_name='دسته\u200cها')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('hero', 'تصویر اصلی'), ('packshot', 'بسته\u200cبندی'), ('lifestyle', 'زندگی / سفره'), ('ingredient', 'مواد اولیه'), ('nutrition_label', 'جدول ارزش غذایی'), ('certificate', 'گواهی\u200cنامه')], default='packshot', max_length=20, verbose_name='نقش')),
                ('image', models.ImageField(upload_to='products/%Y/%m/', verbose_name='تصویر')),
                ('alt_text', models.CharField(blank=True, max_length=220, verbose_name='متن جایگزین')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'تصویر محصول',
                'verbose_name_plural': 'تصاویر محصول',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120, verbose_name='برچسب')),
                ('sku', models.CharField(max_length=64, unique=True, verbose_name='SKU')),
                ('unit_price_rial', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='قیمت (ریال)')),
                ('net_weight_grams', models.PositiveIntegerField(blank=True, null=True, verbose_name='وزن (گرم)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=100, verbose_name='ترتیب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'واریانت',
                'verbose_name_plural': 'واریانت\u200cها',
                'ordering': ['sort_order', 'label'],
            },
        ),
    ]
