# Generated by Django 5.2.17 on 2026-08-31 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_public_uuid_search_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='product_cat_name_4f76a1_idx',
            old_name='product_cat_name_idx',
        ),
        migrations.RenameIndex(
            model_name='category',
            new_name='product_cat_is_acti_1754ef_idx',
            old_name='product_cat_active_kind_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_pro_status_745595_idx',
            old_name='product_prod_status_domain_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='product_pro_sort_or_012c00_idx',
            old_name='product_prod_sort_name_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='product_pro_product_2c49be_idx',
            old_name='product_var_product_active_idx',
        ),
    ]
