# Generated by Django 5.2.17 on 2026-09-04 14:24

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_product_cat_name_idx_product_cat_name_4f76a1_idx_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productvariant',
            options={'ordering': ['sort_order', 'label'], 'verbose_name': 'نوع و اندازه', 'verbose_name_plural': 'نوع و اندازه\u200cها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='domain',
            field=models.CharField(blank=True, choices=[('fresh_meat', 'گوشت تازه'), ('seafood', 'محصولات دریایی'), ('sausage_cold_cuts', 'سوسیس و کالباس'), ('ready_to_cook', 'آماده پخت'), ('ready_meals', 'غذای آماده'), ('dairy', 'لبنیات'), ('agriculture', 'کشاورزی و مزرعه'), ('bakery_culinary', 'نان و آشپزی')], max_length=32, verbose_name='گروه محصول'),
        ),
        migrations.AlterField(
            model_name='category',
            name='kind',
            field=models.CharField(choices=[('navigation', 'منوی فروشگاه'), ('collection', 'مجموعه'), ('seasonal', 'فصلی'), ('promotion', 'پیشنهاد ویژه')], default='navigation', max_length=20, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='category',
            name='public_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=140, unique=True, verbose_name='آدرس صفحه'),
        ),
        migrations.AlterField(
            model_name='product',
            name='allergens',
            field=models.JSONField(blank=True, default=list, verbose_name='مواد حساسیت\u200cزا'),
        ),
        migrations.AlterField(
            model_name='product',
            name='domain',
            field=models.CharField(choices=[('fresh_meat', 'گوشت تازه'), ('seafood', 'محصولات دریایی'), ('sausage_cold_cuts', 'سوسیس و کالباس'), ('ready_to_cook', 'آماده پخت'), ('ready_meals', 'غذای آماده'), ('dairy', 'لبنیات'), ('agriculture', 'کشاورزی و مزرعه'), ('bakery_culinary', 'نان و آشپزی')], max_length=32, verbose_name='گروه محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='public_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='شناسه محصول روی سایت و در جستجو.', unique=True, verbose_name='شناسه محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sales_channel',
            field=models.CharField(choices=[('b2c', 'خرده\u200cفروشی'), ('b2b', 'عمده\u200cفروشی'), ('b2g', 'فروش سازمانی'), ('all_three', 'هر سه')], default='b2c', max_length=16, verbose_name='محل فروش'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=220, unique=True, verbose_name='آدرس صفحه'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='public_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='public_uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='شناسه همین نوع/اندازه؛ به محصول اصلی وصل است.', unique=True, verbose_name='شناسه این نوع'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='sku',
            field=models.CharField(db_index=True, max_length=64, unique=True, validators=[django.core.validators.RegexValidator(message='کد SKU باید ۳ تا ۶۴ کاراکتر، فقط حروف بزرگ انگلیسی، عدد، نقطه، خط تیره و زیرخط باشد.', regex='^[A-Z0-9][A-Z0-9._-]{2,63}$')], verbose_name='کد کالا'),
        ),
    ]
