# Generated by Django 5.2.17 on 2026-09-08 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_insight_and_opinion'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productinsightevent',
            new_name='product_pro_event_t_98f247_idx',
            old_name='product_pro_event_t_4c8a1d_idx',
        ),
        migrations.RenameIndex(
            model_name='productinsightevent',
            new_name='product_pro_product_d41dc2_idx',
            old_name='product_pro_product_7e2b44_idx',
        ),
        migrations.RenameIndex(
            model_name='productopinion',
            new_name='product_pro_product_0010b8_idx',
            old_name='product_pro_product_9a11c2_idx',
        ),
        migrations.RenameIndex(
            model_name='productopinion',
            new_name='product_pro_rating_b37e58_idx',
            old_name='product_pro_rating_5d03aa_idx',
        ),
    ]
