# Generated by Django 5.2.17 on 2026-09-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_rename_product_pro_event_t_4c8a1d_idx_product_pro_event_t_98f247_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('pending_review', 'در انتظار تأیید'), ('active', 'فعال'), ('out_of_stock', 'ناموجود'), ('discontinued', 'توقف تولید'), ('archived', 'بایگانی')], default='active', max_length=20, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='role',
            field=models.CharField(choices=[('hero', 'تصویر اصلی'), ('packshot', 'بسته\u200cبندی'), ('lifestyle', 'زندگی / سفره'), ('ingredient', 'مواد اولیه'), ('nutrition_label', 'جدول ارزش غذایی'), ('certificate', 'گواهی\u200cنامه')], default='hero', max_length=20, verbose_name='نقش'),
        ),
    ]
