# Generated by Django 5.2.17 on 2026-09-12 05:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('open', 'باز'), ('waiting_staff', 'در انتظار پاسخ ادمین'), ('closed', 'بسته (خروج کاربر)')], db_index=True, default='open', max_length=32, verbose_name='وضعیت')),
                ('last_message_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='آخرین پیام')),
                ('customer_last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین خواندن مشتری')),
                ('staff_last_read_at', models.DateTimeField(blank=True, null=True, verbose_name='آخرین خواندن ادمین')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('assigned_staff', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_support_conversations', to=settings.AUTH_USER_MODEL, verbose_name='ادمین پاسخ\u200cگو')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_conversations', to=settings.AUTH_USER_MODEL, verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'گفتگوی پشتیبانی',
                'verbose_name_plural': 'گفتگوهای پشتیبانی',
                'ordering': ['-last_message_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sender_role', models.CharField(choices=[('customer', 'مشتری'), ('staff', 'ادمین'), ('system', 'سیستم')], max_length=16, verbose_name='نقش فرستنده')),
                ('body', models.TextField(max_length=4000, verbose_name='متن')),
                ('client_message_id', models.CharField(blank=True, default='', help_text='برای جلوگیری از پیام تکراری در شبکه کند', max_length=64, verbose_name='شناسه سمت کلاینت')),
                ('whatsapp_notified_at', models.DateTimeField(blank=True, null=True, verbose_name='نوتیف واتساپ')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='support.supportconversation', verbose_name='گفتگو')),
                ('sender_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_messages', to=settings.AUTH_USER_MODEL, verbose_name='کاربر فرستنده')),
            ],
            options={
                'verbose_name': 'پیام پشتیبانی',
                'verbose_name_plural': 'پیام\u200cهای پشتیبانی',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['customer', 'status'], name='support_sup_custome_bb52a2_idx'),
        ),
        migrations.AddIndex(
            model_name='supportconversation',
            index=models.Index(fields=['-last_message_at'], name='support_sup_last_me_5da06f_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['conversation', 'created_at'], name='support_sup_convers_23198a_idx'),
        ),
        migrations.AddIndex(
            model_name='supportmessage',
            index=models.Index(fields=['client_message_id'], name='support_sup_client__acf555_idx'),
        ),
        migrations.AddConstraint(
            model_name='supportmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('client_message_id', ''), _negated=True), fields=('conversation', 'client_message_id'), name='support_unique_client_message'),
        ),
    ]
