MESSAGE_BODY_MAX_LENGTH = 4000
CONVERSATION_STATUS_OPEN = "open"
CONVERSATION_STATUS_WAITING = "waiting_staff"
CONVERSATION_STATUS_CLOSED = "closed"
SENDER_CUSTOMER = "customer"
SENDER_STAFF = "staff"
SENDER_SYSTEM = "system"
