"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.17.
"""

import importlib.util
import os
from pathlib import Path

from datetime import timedelta

from django.templatetags.static import static
from django.urls import reverse_lazy
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / ".env")


def env_bool(name: str, default: bool = False) -> bool:
    value = os.getenv(name)
    if value is None:
        return default
    return value.strip().lower() in {"1", "true", "yes", "on"}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY is not set. Copy backend/django/.env.example to .env")

DEBUG = env_bool("DEBUG", default=True)

ALLOWED_HOSTS = [
    host.strip()
    for host in os.getenv("ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")
    if host.strip()
]


# Application definition

_ASGI_APPS: list[str] = []
if importlib.util.find_spec("daphne") is not None:
    _ASGI_APPS.append("daphne")
else:
    import warnings

    warnings.warn(
        "daphne is not installed; WebSocket via runserver needs: pip install daphne",
        RuntimeWarning,
        stacklevel=1,
    )
_ASGI_APPS.append("channels")

INSTALLED_APPS = [
    # ASGI / WebSocket — daphne باید قبل از staticfiles باشد
    *_ASGI_APPS,
    # Unfold must be before django.contrib.admin
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.forms",
    "unfold.contrib.inlines",
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    # Third-party
    "rest_framework",
    "rest_framework_simplejwt",
    "rest_framework_simplejwt.token_blacklist",
    "corsheaders",
    "django_ckeditor_5",
    # Marde Kuhestan business domains
    "common",
    "accounts.apps.AccountsConfig",
    "product",
    "inventory",
    "orders",
    "payments",
    "logistics",
    "content.apps.ContentConfig",
    "notifications",
    "sec",
]

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "accounts.authentication.CookieJWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticated",
    ),
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 20,
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=10),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=14),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "UPDATE_LAST_LOGIN": True,
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_TOKEN_CLASSES": ("rest_framework_simplejwt.tokens.AccessToken",),
    "TOKEN_OBTAIN_SERIALIZER": "rest_framework_simplejwt.serializers.TokenObtainPairSerializer",
}

AUTH_COOKIE_SAMESITE = os.getenv("AUTH_COOKIE_SAMESITE", "Lax")
AUTH_COOKIE_SECURE = env_bool("AUTH_COOKIE_SECURE", default=not DEBUG)
AUTH_COOKIE_DOMAIN = os.getenv("AUTH_COOKIE_DOMAIN", "").strip() or None

CORS_ALLOWED_ORIGINS = [
    origin.strip()
    for origin in os.getenv(
        "CORS_ALLOWED_ORIGINS",
        "http://localhost:3000,http://127.0.0.1:3000",
    ).split(",")
    if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = list(CORS_ALLOWED_ORIGINS)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "sec.middleware.DDoSMitigationMiddleware",
    "sec.middleware.SlowRequestWatchdogMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "sec.middleware.SecurityHeadersMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
ASGI_APPLICATION = "core.asgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "mardekoohestan_db"),
        "USER": os.getenv("POSTGRES_USER", "mardekoohestan"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", ""),
        "HOST": os.getenv("POSTGRES_HOST", "127.0.0.1"),
        "PORT": os.getenv("POSTGRES_PORT", "55432"),
        "CONN_MAX_AGE": int(os.getenv("DB_CONN_MAX_AGE", "60")),
        "CONN_HEALTH_CHECKS": True,
    }
}


# Password hashers
# https://docs.djangoproject.com/en/5.2/topics/auth/passwords/#using-argon2-with-django
PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
    "django.contrib.auth.hashers.ScryptPasswordHasher",
]

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "fa"

LANGUAGES = [
    ("fa", "فارسی"),
]

TIME_ZONE = "Asia/Tehran"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# CKEditor 5 (writer-friendly rich text in admin)
CKEDITOR_5_FILE_STORAGE = "django.core.files.storage.FileSystemStorage"
CKEDITOR_5_FILE_UPLOAD_PERMISSION = "staff"
CKEDITOR_5_MAX_FILE_SIZE = 8  # MB
CKEDITOR_5_UPLOAD_FILE_TYPES = ["jpeg", "jpg", "png", "gif", "webp"]
CKEDITOR_5_CUSTOM_CSS = "content/admin/ckeditor_content.css"
CKEDITOR_5_USER_LANGUAGE = False

_CK_COLOR_PALETTE = [
    {"color": "hsl(165, 100%, 18%)", "label": "سبز جنگلی"},
    {"color": "hsl(165, 100%, 16%)", "label": "سبز تیره"},
    {"color": "hsl(40, 33%, 93%)", "label": "کرم"},
    {"color": "hsl(11, 56%, 36%)", "label": "خاکی"},
    {"color": "hsl(219, 59%, 30%)", "label": "سرمه‌ای"},
    {"color": "hsl(28, 79%, 42%)", "label": "کهربایی"},
    {"color": "hsl(0, 0%, 11%)", "label": "جوهر"},
    {"color": "hsl(0, 0%, 30%)", "label": "خاکستری"},
]

_SEO_EDITOR_CONFIG = {
    "language": {"ui": "fa", "content": "fa"},
    "toolbar": {
        "items": [
            "heading",
            "|",
            "fontFamily",
            "fontSize",
            "fontColor",
            "fontBackgroundColor",
            "|",
            "bold",
            "italic",
            "underline",
            "strikethrough",
            "highlight",
            "|",
            "alignment",
            "|",
            "link",
            "bulletedList",
            "numberedList",
            "todoList",
            "|",
            "outdent",
            "indent",
            "|",
            "imageUpload",
            "insertImage",
            "mediaEmbed",
            "insertTable",
            "horizontalLine",
            "blockQuote",
            "specialCharacters",
            "|",
            "findAndReplace",
            "removeFormat",
            "sourceEditing",
            "|",
            "undo",
            "redo",
        ],
        "shouldNotGroupWhenFull": True,
    },
    "heading": {
        "options": [
            {
                "model": "paragraph",
                "title": "پاراگراف",
                "class": "ck-heading_paragraph",
            },
            {
                "model": "heading1",
                "view": "h1",
                "title": "عنوان ۱",
                "class": "ck-heading_heading1",
            },
            {
                "model": "heading2",
                "view": "h2",
                "title": "عنوان ۲",
                "class": "ck-heading_heading2",
            },
            {
                "model": "heading3",
                "view": "h3",
                "title": "عنوان ۳",
                "class": "ck-heading_heading3",
            },
            {
                "model": "heading4",
                "view": "h4",
                "title": "عنوان ۴",
                "class": "ck-heading_heading4",
            },
        ]
    },
    "fontFamily": {
        "options": [
            "default",
            "MardeKuhestan",
            "Tahoma",
            "Arial, Helvetica, sans-serif",
            "Georgia, serif",
            "Times New Roman, Times, serif",
            "Courier New, Courier, monospace",
        ],
        "supportAllValues": True,
    },
    "fontSize": {
        "options": [12, 14, "default", 16, 18, 20, 24, 28, 32],
        "supportAllValues": True,
    },
    "fontColor": {
        "colors": _CK_COLOR_PALETTE,
        "columns": 4,
    },
    "fontBackgroundColor": {
        "colors": _CK_COLOR_PALETTE,
        "columns": 4,
    },
    "alignment": {
        "options": ["right", "center", "left", "justify"],
    },
    "image": {
        "toolbar": [
            "imageTextAlternative",
            "toggleImageCaption",
            "|",
            "imageStyle:alignLeft",
            "imageStyle:alignCenter",
            "imageStyle:alignRight",
            "imageStyle:side",
            "|",
            "resizeImage",
            "linkImage",
        ],
        "styles": [
            "full",
            "side",
            "alignLeft",
            "alignRight",
            "alignCenter",
        ],
        "upload": {"types": ["jpeg", "jpg", "png", "gif", "webp"]},
    },
    "table": {
        "contentToolbar": [
            "tableColumn",
            "tableRow",
            "mergeTableCells",
            "tableProperties",
            "tableCellProperties",
            "toggleTableCaption",
        ],
        "tableProperties": {
            "borderColors": _CK_COLOR_PALETTE,
            "backgroundColors": _CK_COLOR_PALETTE,
        },
        "tableCellProperties": {
            "borderColors": _CK_COLOR_PALETTE,
            "backgroundColors": _CK_COLOR_PALETTE,
        },
    },
    "list": {
        "properties": {
            "styles": True,
            "startIndex": True,
            "reversed": True,
        }
    },
    "link": {
        "decorators": {
            "openInNewTab": {
                "mode": "manual",
                "label": "باز شدن در تب جدید",
                "attributes": {
                    "target": "_blank",
                    "rel": "noopener noreferrer",
                },
            },
            "nofollow": {
                "mode": "manual",
                "label": "nofollow (سئو)",
                "attributes": {"rel": "nofollow"},
            },
        }
    },
    "htmlSupport": {
        "allow": [
            {
                "name": "img",
                "attributes": True,
                "classes": True,
                "styles": True,
            },
            {
                "name": "a",
                "attributes": True,
                "classes": True,
                "styles": True,
            },
            {
                "name": "/.*/",
                "attributes": True,
                "classes": True,
                "styles": True,
            },
        ]
    },
}

CKEDITOR_5_CONFIGS = {
    "default": _SEO_EDITOR_CONFIG,
    "extends": _SEO_EDITOR_CONFIG,
}


_MK_COLORS = {
    "primary": {
        "50": "#eef6f4",
        "100": "#d5ebe4",
        "200": "#abd7c9",
        "300": "#75b8a5",
        "400": "#3d927a",
        "500": "#005B48",
        "600": "#005040",
        "700": "#003d32",
        "800": "#002e26",
        "900": "#001f1a",
        "950": "#001411",
    },
}

_MK_STYLES = [
    lambda request: static("admin/mk-admin.css") + "?v=brand-1",
]

# پنل اصلی فروشگاه
UNFOLD = {
    "SITE_TITLE": "مدیریت مرد کوهستان",
    "SITE_HEADER": "مرد کوهستان",
    "SITE_SUBHEADER": "خانهٔ مدیریت فروشگاه",
    "SITE_URL": "/",
    "SITE_SYMBOL": "spa",
    "SITE_LOGO": {
        "light": lambda request: static("admin/brand/logo-full.svg"),
        "dark": lambda request: static("admin/brand/logo-full.svg"),
    },
    "THEME": "light",
    "BORDER_RADIUS": "10px",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "ENVIRONMENT": "core.admin_ui.environment_callback",
    "DASHBOARD_CALLBACK": "core.admin_ui.admin_dashboard_callback",
    "STYLES": _MK_STYLES,
    "COLORS": _MK_COLORS,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "خانه",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "شروع کار",
                        "icon": "home",
                        "link": reverse_lazy("admin:index"),
                        "permission": "core.admin_ui.staff_ok",
                    },
                ],
            },
            {
                "title": "فروشگاه",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "محصول‌ها",
                        "icon": "inventory_2",
                        "link": reverse_lazy("admin:product_product_changelist"),
                        "permission": "core.admin_ui.staff_ok",
                    },
                    {
                        "title": "دسته‌ها",
                        "icon": "category",
                        "link": reverse_lazy("admin:product_category_changelist"),
                        "permission": "core.admin_ui.staff_ok",
                    },
                    {
                        "title": "نوع و اندازه",
                        "icon": "tune",
                        "link": reverse_lazy("admin:product_productvariant_changelist"),
                        "permission": "core.admin_ui.staff_ok",
                    },
                    {
                        "title": "عکس محصول",
                        "icon": "photo_library",
                        "link": reverse_lazy("admin:product_productimage_changelist"),
                        "permission": "core.admin_ui.staff_ok",
                    },
                ],
            },
            {
                "title": "نوشته‌ها",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "مجله",
                        "icon": "menu_book",
                        "link": "/studio/",
                        "permission": "core.admin_ui.staff_ok",
                    },
                ],
            },
            {
                "title": "افراد",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "کاربران",
                        "icon": "group",
                        "link": reverse_lazy("admin:auth_user_changelist"),
                        "permission": "core.admin_ui.staff_ok",
                    },
                    {
                        "title": "گروه‌ها",
                        "icon": "admin_panel_settings",
                        "link": reverse_lazy("admin:auth_group_changelist"),
                        "permission": "core.admin_ui.staff_ok",
                    },
                ],
            },
        ],
    },
}

# پنل مجله و نوشته‌ها
UNFOLD_STUDIO = {
    "SITE_TITLE": "مجله مرد کوهستان",
    "SITE_HEADER": "مجله مرد کوهستان",
    "SITE_SUBHEADER": "نوشتن و گذاشتن مقاله روی سایت",
    "SITE_URL": "/",
    "SITE_SYMBOL": "edit_note",
    "SITE_LOGO": {
        "light": lambda request: static("admin/brand/logo-full.svg"),
        "dark": lambda request: static("admin/brand/logo-full.svg"),
    },
    "THEME": "light",
    "BORDER_RADIUS": "10px",
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": False,
    "ENVIRONMENT": "core.admin_ui.environment_callback",
    "DASHBOARD_CALLBACK": "core.admin_ui.studio_dashboard_callback",
    "STYLES": [
        *_MK_STYLES,
        lambda request: static("content/admin/seo_studio.css") + "?v=brand-1",
    ],
    "COLORS": _MK_COLORS,
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "خانه",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "شروع کار",
                        "icon": "home",
                        "link": "/studio/",
                        "permission": "core.admin_ui.content_panel_ok",
                    },
                ],
            },
            {
                "title": "نوشتن",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "مقاله‌ها",
                        "icon": "article",
                        "link": "/studio/content/article/",
                        "permission": "core.admin_ui.content_panel_ok",
                    },
                ],
            },
            {
                "title": "مرتب‌سازی موضوع",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "موضوع‌های اصلی",
                        "icon": "account_tree",
                        "link": "/studio/content/contentpillar/",
                        "permission": "core.admin_ui.content_panel_ok",
                    },
                    {
                        "title": "زیرموضوع‌ها",
                        "icon": "hub",
                        "link": "/studio/content/topiccluster/",
                        "permission": "core.admin_ui.content_panel_ok",
                    },
                    {
                        "title": "دسته‌بندی مجله",
                        "icon": "category",
                        "link": "/studio/content/category/",
                        "permission": "core.admin_ui.content_panel_ok",
                    },
                    {
                        "title": "برچسب‌ها",
                        "icon": "sell",
                        "link": "/studio/content/tag/",
                        "permission": "core.admin_ui.content_panel_ok",
                    },
                ],
            },
            {
                "title": "آدرس صفحات",
                "separator": True,
                "collapsible": True,
                "items": [
                    {
                        "title": "آدرس‌های قدیمی",
                        "icon": "alt_route",
                        "link": "/studio/content/redirectrule/",
                        "permission": "core.admin_ui.content_panel_ok",
                    },
                ],
            },
        ],
    },
}

# Redis cache
REDIS_URL = os.getenv("REDIS_URL", "redis://127.0.0.1:6379/0")
CHANNEL_REDIS_URL = os.getenv("CHANNEL_REDIS_URL", "redis://127.0.0.1:6379/2")

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [CHANNEL_REDIS_URL],
            "capacity": 1500,
            "expiry": 30,
        },
    },
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": REDIS_URL,
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": int(os.getenv("REDIS_MAX_CONNECTIONS", "100")),
                "retry_on_timeout": True,
                "socket_timeout": 1,
                "socket_connect_timeout": 1,
            },
            "SOCKET_TIMEOUT": 1,
            "SOCKET_CONNECT_TIMEOUT": 1,
            "IGNORE_EXCEPTIONS": True,
        },
    }
}

# Celery (Enterprise Queueing, Anti-OOM & Fail-safe Task Routing)
CELERY_BROKER_URL = os.getenv(
    "CELERY_BROKER_URL",
    os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
)
CELERY_RESULT_BACKEND = os.getenv(
    "CELERY_RESULT_BACKEND",
    os.getenv("REDIS_URL", "redis://127.0.0.1:6379/1"),
)
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_TIMEZONE = TIME_ZONE
CELERY_WORKER_PREFETCH_MULTIPLIER = 1
CELERY_WORKER_MAX_TASKS_PER_CHILD = 500
CELERY_WORKER_MAX_MEMORY_PER_CHILD = 350000
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_TASK_SOFT_TIME_LIMIT = 120
CELERY_TASK_TIME_LIMIT = 180

# Kafka
KAFKA_BOOTSTRAP_SERVERS = os.getenv("KAFKA_BOOTSTRAP_SERVERS", "127.0.0.1:9092")

# OpenSearch
OPENSEARCH_HOST = os.getenv("OPENSEARCH_HOST", "127.0.0.1")
OPENSEARCH_PORT = int(os.getenv("OPENSEARCH_PORT", "9200"))
OPENSEARCH_USER = os.getenv("OPENSEARCH_USER", "admin")
OPENSEARCH_PASSWORD = os.getenv("OPENSEARCH_PASSWORD", "")

# MinIO / S3 storage
AWS_ACCESS_KEY_ID = os.getenv("MINIO_ROOT_USER", "")
AWS_SECRET_ACCESS_KEY = os.getenv("MINIO_ROOT_PASSWORD", "")
AWS_STORAGE_BUCKET_NAME = os.getenv("MINIO_BUCKET_NAME", "mardekoohestan")
AWS_S3_ENDPOINT_URL = os.getenv("MINIO_ENDPOINT_URL", "http://127.0.0.1:9010")
AWS_S3_REGION_NAME = os.getenv("MINIO_REGION", "us-east-1")
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL = None

# ---------------------------------------------------------------------------
# Security — production hardening
# ---------------------------------------------------------------------------

TRUST_X_FORWARDED_FOR = env_bool("TRUST_X_FORWARDED_FOR", default=False)
RATE_LIMIT_FAIL_CLOSED = env_bool("RATE_LIMIT_FAIL_CLOSED", default=not DEBUG)

DATA_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024  # 6 MB (تصاویر کاتالوگ)
FILE_UPLOAD_MAX_MEMORY_SIZE = 6 * 1024 * 1024

if not DEBUG:
    SECURE_SSL_REDIRECT = env_bool("SECURE_SSL_REDIRECT", default=True)
    SECURE_HSTS_SECONDS = int(os.getenv("SECURE_HSTS_SECONDS", "31536000"))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = env_bool("SECURE_HSTS_PRELOAD", default=False)
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    AUTH_COOKIE_SECURE = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    SECURE_REFERRER_POLICY = "same-origin"
    X_FRAME_OPTIONS = "DENY"
