# Generated by Django 5.2.17 on 2026-09-05 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سبد خرید',
                'verbose_name_plural': 'سبدهای خرید',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه محصول')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('product_image', models.CharField(blank=True, default='/brand/home-meat.png', max_length=500, verbose_name='تصویر محصول')),
                ('portion', models.CharField(blank=True, default='۱ کیلوگرم', max_length=100, verbose_name='وزن / سهمیه')),
                ('cut_type', models.CharField(blank=True, default='برش استاندارد', max_length=100, verbose_name='نوع برش')),
                ('unit_price_toman', models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد (تومان)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ افزودن')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.cart', verbose_name='سبد خرید')),
            ],
            options={
                'verbose_name': 'قلم سبد خرید',
                'verbose_name_plural': 'اقلام سبد خرید',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='شماره سفارش')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('processing', 'در حال آماده\u200cسازی در مرتع'), ('shipping', 'در مسیر تحویل (زنجیره سرد)'), ('delivered', 'تحویل\u200cشده با زنجیره سرد'), ('cancelled', 'لغو شده')], default='pending', max_length=30, verbose_name='وضعیت سفارش')),
                ('pasture_name', models.CharField(default='مرتع ییلاقی کلاردشت (دامنه مازیچال)', max_length=200, verbose_name='نام و موقعیت چراگاه')),
                ('altitude', models.CharField(default='۲,۲۰۰ متر از سطح دریا', max_length=100, verbose_name='ارتفاع از سطح دریا')),
                ('grazing_info', models.CharField(default='علوفه وحشی کوهپایه و آویشن ارگانیک', max_length=200, verbose_name='پوشش گیاهی و چرا')),
                ('vet_code', models.CharField(default='IR-88301 نظام دامپزشکی', max_length=100, verbose_name='کد بهداشت دامپزشکی')),
                ('pack_date', models.CharField(default='۱۰ شهریور ۱۴۰۵ - ۰۶:۳۰', max_length=100, verbose_name='تاریخ و ساعت بسته\u200cبندی')),
                ('temperature_log', models.CharField(default='۲.۴°C (زنجیره سرد کنترل\u200cشده)', max_length=100, verbose_name='پایش دما')),
                ('receiver_name', models.CharField(blank=True, default='', max_length=120, verbose_name='نام تحویل\u200cگیرنده')),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=40, verbose_name='شماره همراه تحویل\u200cگیرنده')),
                ('shipping_address', models.TextField(blank=True, default='', verbose_name='نشانی دقیق تحویل')),
                ('delivery_notice', models.CharField(blank=True, default='تحویل ظرف ۲ الی ۳ روز کاری با هماهنگی تلفنی قبلی', max_length=300, verbose_name='تذکر هماهنگی')),
                ('total_amount_toman', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کل (تومان)')),
                ('discount_amount_toman', models.PositiveBigIntegerField(default=0, verbose_name='تخفیف سهمیه (تومان)')),
                ('final_amount_toman', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ نهایی پرداخت\u200cشده (تومان)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین بروزرسانی')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='کاربر خریدار')),
            ],
            options={
                'verbose_name': 'سفارش و بارنامه',
                'verbose_name_plural': 'سفارش\u200cها و بارنامه\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255, verbose_name='نام بسته / برش')),
                ('product_image', models.CharField(blank=True, default='/brand/home-meat.png', max_length=500, verbose_name='تصویر')),
                ('cut_type', models.CharField(blank=True, default='برش استریل بدون چربی اضافی', max_length=100, verbose_name='نوع برش')),
                ('portion', models.CharField(blank=True, default='۱ کیلوگرم', max_length=100, verbose_name='اندازه / وزن')),
                ('unit_price_toman', models.PositiveBigIntegerField(default=0, verbose_name='قیمت واحد (تومان)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('total_price_toman', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ کل (تومان)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='سفارش')),
            ],
            options={
                'verbose_name': 'قلم سفارش',
                'verbose_name_plural': 'اقلام سفارش\u200cها',
            },
        ),
    ]
