# Generated by Django 5.2.17 on 2026-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('confirmed', 'تایید شده'), ('processing', 'در حال آماده\u200cسازی در مرتع'), ('shipping', 'در مسیر تحویل (زنجیره سرد)'), ('delivered', 'تحویل\u200cشده با زنجیره سرد'), ('cancelled', 'لغو شده')], default='pending', max_length=30, verbose_name='وضعیت سفارش'),
        ),
    ]
