# Generated by Django 5.2.17 on 2026-09-07 07:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='شناسه عمومی')),
                ('gateway', models.CharField(choices=[('zarinpal', 'زرین\u200cپال'), ('parsian', 'پارسیان')], max_length=20, verbose_name='درگاه')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت\u200cشده'), ('failed', 'ناموفق'), ('canceled', 'انصراف')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('amount_toman', models.PositiveBigIntegerField(default=0, verbose_name='مبلغ (تومان)')),
                ('authority', models.CharField(blank=True, default='', max_length=120, verbose_name='کد پیگیری درگاه')),
                ('ref_id', models.CharField(blank=True, default='', max_length=120, verbose_name='شماره مرجع')),
                ('sandbox', models.BooleanField(default=True, verbose_name='سندباکس')),
                ('receiver_name', models.CharField(blank=True, default='', max_length=120, verbose_name='تحویل\u200cگیرنده')),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=40, verbose_name='تلفن')),
                ('shipping_address', models.TextField(blank=True, default='', verbose_name='نشانی')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='بروزرسانی')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='orders.order', verbose_name='سفارش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پرداخت',
                'verbose_name_plural': 'پرداخت\u200cها',
                'ordering': ['-created_at'],
            },
        ),
    ]
