# Generated by Django 5.2.17 on 2026-09-15 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purpose',
            field=models.CharField(choices=[('cart', 'سبد خرید'), ('ai_coach', 'اشتراک راهیار تغذیه')], db_index=True, default='cart', max_length=20, verbose_name='نوع پرداخت'),
        ),
    ]
