# Generated by Django 5.2.17 on 2026-09-15 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AiCoachQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('free_used', models.PositiveSmallIntegerField(default=0, verbose_name='سوال رایگان مصرف\u200cشده')),
                ('paid_remaining', models.PositiveIntegerField(default=0, verbose_name='سوال پولی باقی\u200cمانده')),
                ('paid_total', models.PositiveIntegerField(default=0, verbose_name='کل سوال پولی خریداری\u200cشده')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_coach_quotas', to='payments.payment', verbose_name='آخرین پرداخت اشتراک')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_coach_quota', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سهمیه راهیار تغذیه',
                'verbose_name_plural': 'سهمیه\u200cهای راهیار تغذیه',
            },
        ),
        migrations.CreateModel(
            name='WaitlistInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_key', models.CharField(db_index=True, max_length=80, verbose_name='کلید محصول')),
                ('product_name', models.CharField(max_length=200, verbose_name='نام محصول')),
                ('source', models.CharField(default='product-unveil', max_length=80, verbose_name='منبع')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='موبایل')),
                ('display_name', models.CharField(blank=True, default='', max_length=120, verbose_name='نام')),
                ('notified_admin', models.BooleanField(default=False, verbose_name='ایمیل به ادمین ارسال شد')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='ثبت')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waitlist_interests', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'علاقه به محصول به\u200cزودی',
                'verbose_name_plural': 'علاقه\u200cمندی\u200cهای به\u200cزودی (خبرم کن)',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'product_key'), name='uniq_waitlist_user_product')],
            },
        ),
    ]
