# Generated by Django 5.2.17 on 2026-09-04 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='نشانی منزل', max_length=100, verbose_name='عنوان نشانی')),
                ('address_type', models.CharField(choices=[('home', 'منزل'), ('work', 'محل کار / دفتر'), ('other', 'سایر نشانی\u200cها')], default='home', max_length=20, verbose_name='نوع نشانی')),
                ('province', models.CharField(default='تهران', max_length=100, verbose_name='استان')),
                ('city', models.CharField(default='تهران', max_length=100, verbose_name='شهر')),
                ('district', models.CharField(blank=True, default='زعفرانیه', max_length=120, verbose_name='منطقه / محله')),
                ('address_line', models.TextField(max_length=500, verbose_name='نشانی دقیق و پلاک')),
                ('postal_code', models.CharField(blank=True, default='', max_length=30, verbose_name='کد پستی')),
                ('receiver_name', models.CharField(blank=True, default='', max_length=120, verbose_name='نام تحویل\u200cگیرنده')),
                ('receiver_phone', models.CharField(blank=True, default='', max_length=40, verbose_name='تلفن تحویل\u200cگیرنده')),
                ('is_default', models.BooleanField(default=False, verbose_name='نشانی پیش\u200cفرض')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'نشانی تحویل مشتری',
                'verbose_name_plural': 'نشانی\u200cهای تحویل مشتریان',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
