# Generated by Django 5.2.17 on 2026-09-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='avatars/%Y/%m/', verbose_name='تصویر پروفایل'),
        ),
    ]
